packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@payloadcms/ui": ^3.39.1
  "@payloadcms/richtext-lexical": ^3.39.1
  "@payloadcms/email-resend": ^3.39.1
  "@payloadcms/db-postgres": ^3.39.1
  "@payloadcms/db-sqlite": ^3.39.1
  "@payloadcms/next": ^3.39.1
  "@payloadcms/payload-cloud": ^3.39.1
  "@payloadcms/plugin-nested-docs": ^3.39.1
  "@payloadcms/storage-s3": ^3.39.1
  "payload": ^3.39.1
  "react": ^19.1.0
  "react-dom": ^19.1.0
  "react-is": ^19.1.0
  "typescript": ^5.8.3
  "tailwindcss": ^4.1.3
  "@tailwindcss/postcss": ^4.1.3
  "@types/node": ^22.5.4
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.1
  "@types/react-is": ^19.0.0
  "zod": ^3.24.3
  "lucide-react": ^0.488.0
  "@react-three/fiber": ^9.1.2
  "@react-three/drei": ^10.0.6
  "three": ^0.175.0
  "react-hook-form": ^7.56.1
  "next": ^15.3.2
