packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@payloadcms/ui": ^3.34.0
  "@payloadcms/richtext-lexical": ^3.34.0
  "@payloadcms/plugin-seo": ^3.34.0
  "@payloadcms/email-resend": ^3.34.0
  "@payloadcms/db-postgres": ^3.34.0
  "@payloadcms/storage-s3": ^3.34.0
  "@payloadcms/next": ^3.34.0
  "@payloadcms/payload-cloud": ^3.34.0
  "payload": ^3.34.0
  "@tabler/icons": ^3.31.0
  "react": ^19.1.0
  "react-dom": ^19.1.0
  "typescript": ^5.8.3
  "tailwindcss": ^4.1.3
  "@types/node": ^22.5.4
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.1