import type { Metadata } from "next";

import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { JotaiProvider } from "~/components/jotai-provider.client";
import { CookieConsent } from "~/components/cookie-consent.client";
import { ThemeProvider } from "~/components/theme-provider.client";
import { SidebarInset, SidebarProvider } from "~/components/sidebar.client";
import { Header } from "~/layouts/header-layout.server";
import { Footer } from "~/layouts/footer-layout.server";
import { WebVitals } from "~/components/web-vitals.client";

import { isValidLocale } from "~/utils/is-valid-locale";

import "@synoem/ui/web.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!isValidLocale(locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <head>
        {/* <script src="https://cdn.jsdelivr.net/npm/react-scan/dist/auto.global.js" /> */}
      </head>
      <body
        className="flex min-h-screen flex-col antialiased [--header-height:calc(theme(spacing.14))]"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WebVitals />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <JotaiProvider>
            <NextIntlClientProvider locale={locale}>
              <SidebarProvider className="flex flex-col">
                <Header locale={locale} />
                <SidebarInset className="w-full max-w-none flex-1 mx-auto p-4 md:p-8">
                  {children}
                </SidebarInset>
                <CookieConsent />
                <Footer locale={locale} />
              </SidebarProvider>
            </NextIntlClientProvider>
          </JotaiProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
