name: Build & Deploy CMS

on:
  push:
    paths:
      - "apps/cms/**"
      - "packages/**"
      - "!apps/web/**"
    branches-ignore:
      - "main"
  pull_request:
    paths:
      - "apps/cms/**"
      - "packages/**"
      - "!apps/web/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install

      - name: Inject DMNO env for CMS
        uses: dmno/dmno-gh-action@v1
        with:
          service-name: "cms"

      - name: Build CMS
        run: pnpm --filter @synoem/cms run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: pnpm --filter @synoem/cms run preview
