name: Build & Deploy CMS

env:
  DMNO_VAULT_KEY_PROD: ${{ secrets.DMNO_VAULT_KEY_PROD }}

on:
  pull_request:
    paths:
      - "apps/cms/**"
      - "packages/**"
      - "!apps/web/**"
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Inject DMNO env for CMS
        uses: dmno/dmno-gh-action@v1
        with:
          service-name: "cms"

      - name: Build CMS
        run: pmpm --filter @synoem/cms run build

      - name: Deploy to Vercel
        run: pnpm --filter @synoem/cms run deploy
        env:
          VERCEL_TOKEN: ${{env.VERCEL_TOKEN}}
          VERCEL_PROJECT_ID: ${{env.VERCEL_PROJECT_ID}}
          VERCEL_ORG_ID: ${{env.VERCEL_ORG_ID}}
